import { APIURL } from "./Constants";

export const VENUES = APIURL + "get-venues"
export  const SIGNUP = APIURL + "register"
export const LOGIN = APIURL + "login"
export const UPLOAD_VENUE = APIURL + "upload-venue"
export const UPLOAD_CATEGORY = APIURL + "upload-category"
export const UPLOAD_DISH = APIURL + "upload-dish"
export const ADD_DISH = APIURL + "relate-dish-venue"
export const GET_TOTAL_USERS= APIURL + "total-users"
export const GET_BOOKING = APIURL + "get-bookings"
export const UPDATE_PROFILE = APIURL + "update-profile"
export const CHANGE_PASSWORD = APIURL + "change-password"
export const GET_USER_Bookings = APIURL + "booking"
export const VENUE_BOOKING = APIURL + "booking"
export const VENUE_BOOKING_DELETE = APIURL + "delete-booking-by-date-and-venue"
